language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install coveralls nose
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
script:
  - coverage run --source=black_magic setup.py nosetests
after_success:
  - coveralls
