language: python
sudo: false
python:
# - "2.6"       # support removed on travis
  - "2.7"
# - "3.3"       # support removed on travis
  - "3.4"
  - "3.5"
  - "3.6"
# - "3.7"       # dist=xenial, see below
  - "pypy"
# Works on my machine, fails on Travis:
# - "pypy3"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install coveralls nose
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
script:
  - coverage run --source=black_magic setup.py nosetests --with-doctest --exclude=benchmark
after_success:
  - coveralls
